# Generated by Django 2.1.2 on 2019-02-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='user_images')),
            ],
        ),
    ]
