# Generated by Django 2.1.2 on 2019-02-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20190213_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='score',
        ),
        migrations.AddField(
            model_name='human',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='human',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='human',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='human',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='user_images'),
        ),
    ]
