# Generated by Django 2.1.2 on 2019-02-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20190215_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
